spring:
  application:
    name: stats-server
  datasource:
    url: jdbc:postgresql://localhost:5432/stats_db
    username: stats_user
    password: stats_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 9090
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health, info